alerts:
  - changed-files:
    - any-glob-to-any-file: 'alerts/**'

api:
  - changed-files:
    - any-glob-to-any-file: 'api/**'

scraper:
  - changed-files:
    - any-glob-to-any-file: 'scraper/**'

webui:
  - changed-files:
    - any-glob-to-any-file: 'webui/**'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - 'docker-compose*.yml'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**.md'
      - 'docs/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file: '**/requirements*.txt'
