# .github/labeler.yml
# Auto-label baserat på ändrade filer
docker:
  - changed-files:
      - any-glob-to-any-file: '**/Dockerfile'

python:
  - changed-files:
      - any-glob-to-any-file: '**/*.py'
      - any-glob-to-any-file: '**/requirements.txt'

documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

scraper:
  - changed-files:
      - any-glob-to-any-file: 'scraper/**/*'

api:
  - changed-files:
      - any-glob-to-any-file: 'api/**/*'

webui:
  - changed-files:
      - any-glob-to-any-file: 'webui/**/*'

alerts:
  - changed-files:
      - any-glob-to-any-file: 'alerts/**/*'

auto-merge:
  - head-branch: ['^dependabot/']
